# AUTOGENERATED! DO NOT EDIT! File to edit: ../00_core.ipynb.

# %% auto 0
__all__ = ['Contact']

# %% ../00_core.ipynb 2
from fastcore.utils import *

# %% ../00_core.ipynb 4
class Contact:
    "Create a contact from a Person and Email"
    def __init__(self,
                 person:Person, # `Person` of the contact
                 email:str, # Email of the contact
                ):
        self.name=person.first_name + ' ' + person.last_name
        self.email=email
        self.job = person.occupation
    def __str__(self): 
        if len(self.job) > 0:
            return f"{self.name} ({self.email}) [{self.job}]"
        else:
            return f"{self.name} ({self.email})"
    __repr__ = __str__

# %% ../00_core.ipynb 9
@patch
def __eq__(self:Contact, c:Contact): return (self.name, self.email)==(c.name, c.email)
