# AUTOGENERATED! DO NOT EDIT! File to edit: ../02_models.ipynb.

# %% auto 0
__all__ = ['PersonBase', 'Person', 'PersonRead', 'PersonCreate', 'PersonUpdate']

# %% ../02_models.ipynb 2
from fastcore.utils import *
from sqlmodel import SQLModel, Field, Relationship

# %% ../02_models.ipynb 4
class PersonBase(SQLModel):
    first_name: str
    last_name: Optional[str] = ''
    occupation: Optional[str] = ''
        
class Person(PersonBase, table=True):
    id: Optional[int] = Field(default=None, primary_key=True)
        
class PersonRead(PersonBase):
    id: int

class PersonCreate(PersonBase):
    pass

class PersonUpdate(SQLModel):
    first_name: Optional[str] = ''
    last_name: Optional[str] = ''
    occupation: Optional[str] = ''
